name: SearXNG
services:
  searxng:
    # https://docs.searxng.org/admin/installation-docker.html
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    env_file: searxng.env
    networks:
      - searxng
      - traefik
    expose:
      - 8080
    volumes:
      - searxng-data:/etc/searxng:rw
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    labels:
      traefik.enable: true
      traefik.http.routers.searxng.rule: Host(`searxng.domain.tld`)
      traefik.http.routers.searxng.entrypoints: https
      traefik.http.routers.searxng.middlewares: local-ip-ranges@file
      traefik.http.routers.searxng.service: searxng
      traefik.http.services.searxng.loadbalancer.server.port: 8080

  searxng-valkey:
    # https://hub.docker.com/r/valkey/valkey/
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - searxng-valkey-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

volumes:
  searxng-valkey-data:
    name: searxng-valkey-data
  searxng-data:
    name: searxng-data

networks:
  searxng:
    name: searxng
  traefik:
    external: true