name: Wyoming

services:
  whisper:
    # https://docs.linuxserver.io/images/docker-faster-whisper/
    image: lscr.io/linuxserver/faster-whisper:gpu
    container_name: wyoming-whisper
    restart: unless-stopped
    runtime: nvidia
    env_file: whisper.env
    networks:
      - wyoming
    expose:
      - 10300
    volumes:
      - whisper:/config

  wyoming-piper:
    # https://docs.linuxserver.io/images/docker-piper/
    image: lscr.io/linuxserver/piper:gpu
    container_name: wyoming-piper
    restart: unless-stopped
    runtime: nvidia
    env_file: piper.env
    networks:
      - wyoming
    expose:
     - 10200
    volumes:
      - piper:/config

volumes:
  whisper:
    name: wyoming-whisper
  piper:
    name: wyoming-piper

networks:
  wyoming:
    name: wyoming