version: '3.9'

services:
  postgresql:
    image: bitnami/postgresql:16.1.0
    container_name: keycloak-db
    restart: unless-stopped
    networks:
      - keycloak
    env_file: .env
    volumes:
      - keycloak-db:/bitnami/postgresql
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro

networks:
  postgresql:
    name: postgresql