version: '3.9'

services:
  caddy:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    init: true
    env_file: .env
    ports:
      - 80:80/tcp
      - 80:80/udp
      - 443:443/tcp
      - 443:443/udp
    networks:
      - caddy
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro

volumes:
  caddy:
    name: caddy

networks:
  caddy:
    name: caddy