name: Jupyter
services:
  jupyter-notebook:
    # https://hub.docker.com/r/jupyter/minimal-notebook/
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter-notebook
    restart: unless-stopped
    command: "start-notebook.py --NotebookApp.token=<tokenhere>"
    volumes:
      - jupyter-notebook:/home/jovyan
      - jupyter-conda-envs:/opt/conda/envs
      - jupyter-conda-pkgs:/opt/conda/pkgs
    networks:
      - jupyter
      - traefik
    expose:
      - 8080
    labels:
      traefik.enable: true
      traefik.http.routers.jupyter.rule: Host(`jupyter.domain.tld`)
      traefik.http.routers.jupyter.entrypoints: https
      traefik.http.routers.jupyter.service: jupyter
      traefik.http.services.jupyter.loadbalancer.server.port: 8888

volumes:
  jupyter-notebook:
    name: jupyter-notebook
  jupyter-conda-envs:
    name: jupyter-conda-envs
  jupyter-conda-pkgs:
    name: jupyter-conda-pkgs

networks:
  jupyter:
    name: jupyter
  traefik:
    external: true