version: '3.9'

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    networks:
      - plex # runs on port 32400 with example conf
    env_file: .env
    environment:
      - VERSION=docker
    #      - PLEX_CLAIM=
    volumes:
      - ./config/plex/:/config
      - ./media/:/media

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.0-develop
    container_name: sonarr
    restart: unless-stopped
    networks:
      - plex
    env_file: .env
    environment:
      - DOCKER_MODS=gilbn/theme.park:sonarr
    volumes:
      - ./config/sonarr/:/config/
      - ./media/:/media/
      - ./tmp/.import:/media/.import
      - ./tmp/downloads/:/downloads/deluge/

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    networks:
      - plex
    env_file: .env
    environment:
      - DOCKER_MODS=gilbn/theme.park:radarr
    volumes:
      - ./config/radarr/:/config/
      - ./media/:/media/
      - ./tmp/.import/:/media/.import/
      - ./tmp/downloads/:/downloads/deluge/

  deluge:
    image: binhex/arch-delugevpn
    container_name: deluge
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - plex
    env_file:
      - .env
      - deluge.env
    volumes:
      - ./config/deluge/:/config/
      - ./tmp/blackhole/:/blackhole/
      - ./tmp/downloads/:/downloads/deluge/

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    networks:
      - plex
    env_file: .env
    environment:
      - AUTO_UPDATE=false
      - DOCKER_MODS=gilbn/theme.park:jackett
    volumes:
      - ./config/jackett/:/config/
      - ./tmp/blackhole/:/blackhole/

networks:
  plex:
    name: plex