services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - uptime-kuma:/app/data
#    networks:
#      - caddy

volumes:
  uptime-kuma:
    name: uptime-kuma

#networks:
#  caddy:
#    external: true