name: Jellyfin
services:
  jellyfin:
    # https://docs.linuxserver.io/images/docker-jellyfin/
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    runtime: nvidia
    env_file: jellyfin.env
    networks:
      - jellyfin
      - traefik
    expose:
      - 8096
    volumes:
      - jellyfin:/config
      - /mnt/media-share:/data
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`jelly.domain.tld`)
      traefik.http.routers.jellyfin.entrypoints: https
      traefik.http.routers.jellyfin.middlewares: local-ip-ranges@file
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096

volumes:
  jellyfin:
    name: jellyfin

networks:
  jellyfin:
    name: jellyfin
  traefik:
    external: true