AUTO_UPGRADE='1'
DNS_API="dns_cf"
ACME_SH_EMAIL="acme@domain.tld"
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
CF_Token=''