#version: '3.9'

services:
  keycloak:
    image: bitnami/keycloak:23.0.4
    container_name: keycloak
    restart: unless-stopped
    networks:
      - keycloak
    depends_on:
      - keycloak-db
    env_file: .env
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro

  keycloak-db:
    image: bitnami/postgresql:16.1.0
    container_name: keycloak-db
    restart: unless-stopped
    networks:
      - keycloak
    env_file: .env
    volumes:
      - keycloak-db:/bitnami/postgresql
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro

volumes:
  keycloak-db:
    name: keycloak-db
networks:
  keycloak:
    name: keycloak