services:
  coredns:
    image: coredns/coredns
    container_name: coredns
    restart: always
    command: -conf /etc/coredns/Corefile
    hostname: domain.tld
    user: 0:0
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./Corefile:/etc/coredns/Corefile
      - ./hosts.conf:/etc/coredns/hosts.conf
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro