version: '3.9'

services:
  coredns:
    image: coredns/coredns:1.10.0
    container_name: coredns
#    platform: linux/arm64
    restart: always
    command: -conf /etc/coredns/Corefile
    hostname: domain.tld
    user: 0:0
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./config:/etc/coredns
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro