name: Ollama
services:
  ollama:
    # https://github.com/ollama/ollama
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    env_file: ollama.env
    networks:
      - ollama
    expose:
      - 11434
    volumes:
      - ollama:/root/.ollama

  ollama-open-webui:
    # https://github.com/open-webui/open-webui
    container_name: ollama-open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    env_file: ollama-open-webui.env
    depends_on:
      - ollama
    networks:
      - ollama
      - traefik
    expose:
      - 8080
    volumes:
      - open-webui:/app/backend/data
    labels:
      traefik.enable: true
      traefik.http.routers.open-webui.rule: Host(`ollama.domain.tld`)
      traefik.http.routers.open-webui.entrypoints: https
      traefik.http.routers.open-webui.middlewares: local-ip-ranges@file
      traefik.http.routers.open-webui.service: open-webui
      traefik.http.services.open-webui.loadbalancer.server.port: 8080

volumes:
  ollama:
    name: ollama
  open-webui:
    name: open-webui

networks:
  ollama:
    name: ollama
  traefik:
    external: true