name: Torrent

services:
  sonarr:
    # https://docs.linuxserver.io/images/docker-sonarr/
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    env_file: sonarr.env
    networks:
      - qbittorrent
      - traefik
    expose:
      - 8989
    volumes:
      - sonarr:/config/
      - /mnt/media-share/video:/media/video
      - /mnt/media-share/import:/media/import
      - /mnt/cache/.import:/downloads/.import
      - /mnt/cache/:/downloads:ro
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.domain.tld`)
      traefik.http.routers.sonarr.entrypoints: https
      traefik.http.routers.sonarr.middlewares: local-ip-ranges@file
      traefik.http.routers.sonarr.service: sonarr
      traefik.http.services.sonarr.loadbalancer.server.port: 8989

  radarr:
    # https://docs.linuxserver.io/images/docker-radarr/
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    env_file: radarr.env
    networks:
      - qbittorrent
      - traefik
    expose:
      - 7878
    volumes:
      - radarr:/config/
      - /mnt/media-share/video:/media/video
      - /mnt/media-share/import:/media/import
      - /mnt/cache/.import:/downloads/.import
      - /mnt/cache/:/downloads:ro
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr.domain.tld`)
      traefik.http.routers.radarr.entrypoints: https
      traefik.http.routers.radarr.middlewares: local-ip-ranges@file
      traefik.http.routers.radarr.service: radarr
      traefik.http.services.radarr.loadbalancer.server.port: 7878

  lidarr:
    # https://docs.linuxserver.io/images/docker-lidarr/
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    env_file: lidarr.env
    networks:
      - qbittorrent
      - traefik
    expose:
      - 8686
    volumes:
      - lidarr:/config/
      - /mnt/media-share/audio:/media/audio
      - /mnt/media-share/import:/media/import
      - /mnt/cache/.import:/downloads/.import
      - /mnt/cache/:/downloads:ro
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.rule: Host(`lidarr.domain.tld`)
      traefik.http.routers.lidarr.entrypoints: https
      traefik.http.routers.lidarr.middlewares: local-ip-ranges@file
      traefik.http.routers.lidarr.service: lidarr
      traefik.http.services.lidarr.loadbalancer.server.port: 8686

  jackett:
    # https://docs.linuxserver.io/images/docker-jackett/
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    env_file: jackett.env
    networks:
      - traefik
    expose:
      - 9117
    volumes:
      - jackett:/config/
      - blackhole:/blackhole/
    labels:
      traefik.enable: true
      traefik.http.routers.jackett.rule: Host(`jackett.domain.tld`)
      traefik.http.routers.jackett.entrypoints: https
      traefik.http.routers.jackett.middlewares: local-ip-ranges@file
      traefik.http.routers.jackett.service: jackett
      traefik.http.services.jackett.loadbalancer.server.port: 9117

  qbittorrent:
    # https://github.com/binhex/arch-qbittorrentvpn
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrent
    restart: unless-stopped
    env_file: qbittorrent.env
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    privileged: true
    devices:
      - /dev/net/tun
    networks:
      - qbittorrent
      - traefik
    expose:
      - 8080
    volumes:
      - qbittorrent:/config/
      #      - ./wg0.conf:/config/wireguard/wg0.conf
      - blackhole:/downloads/.blackhole/
      - /mnt/cache/:/downloads/
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.domain.tld`)
      traefik.http.routers.qbittorrent.entrypoints: https
      traefik.http.routers.qbittorrent.middlewares: local-ip-ranges@file
      traefik.http.routers.qbittorrent.service: qbittorrent
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080

volumes:
  sonarr:
    name: sonarr
  radarr:
    name: radarr
  lidarr:
    name: lidarr
  jackett:
    name: jackett
  blackhole:
    name: blackhole
  qbittorrent:
    name: qbittorrent

networks:
  qbittorrent:
    name: qbittorrent
  traefik:
    external: true