http:
  routers:
    redirect-http-to-https:
      entrypoints:
        - http
      rule: PathPrefix(`/`)
      middlewares:
        - redirect-http-to-https
      service: noop@internal

  middlewares:
    redirect-http-to-https:
      redirectScheme:
        scheme: https
        permanent: true