services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DOCKER_MODS=gilbn/theme.park:sonarr
      - PUID=1000
      - PGID=1000
    networks:
      - torrent
#      - caddy
    volumes:
      - sonarr:/config/
      - /mnt/media-share/video:/media/video
      - /mnt/download-cache/.import:/downloads/.import
      - /mnt/download-cache/:/downloads:ro
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DOCKER_MODS=gilbn/theme.park:radarr
      - PUID=1000
      - PGID=1000
    networks:
      - torrent
#      - caddy
    volumes:
      - radarr:/config/
      - /mnt/media-share/video:/media/video
      - /mnt/download-cache/.import:/downloads/.import
      - /mnt/download-cache/:/downloads:ro
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DOCKER_MODS=gilbn/theme.park:lidarr
      - PUID=1000
      - PGID=1000
    networks:
      - torrent
#      - caddy
    volumes:
      - lidarr:/config/
      - /mnt/media-share/audio:/media/audio
      - /mnt/download-cache/.import:/downloads/.import
      - /mnt/download-cache/:/downloads:ro
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - AUTO_UPDATE=false
      - DOCKER_MODS=gilbn/theme.park:jackett
      - PUID=1000
      - PGID=1000
    networks:
#      - caddy
      - torrent
    volumes:
      - jackett:/config/
      - blackhole:/blackhole/

  deluge:
    image: binhex/arch-delugevpn
    container_name: deluge
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_ENABLED=yes
      - VPN_PROV=custom
      - VPN_CLIENT=openvpn
      - STRONG_CERTS=yes
      - ENABLE_PRIVOXY=no
      - LAN_NETWORK=192.168.0.0/16
      - NAME_SERVERS=1.1.1.1,1.0.0.1
    networks:
#      - caddy
      - torrent
    volumes:
      - deluge:/config/
      - ./server.ovpn:/config/openvpn/server.ovpn
      - ./credentials.conf:/config/openvpn/credentials.conf
      - blackhole:/blackhole/
      - /mnt/download-cache/:/downloads
#  qbittorrent:
#    image: dyonr/qbittorrentvpn
#    container_name: qbittorrent
#    restart: unless-stopped
#    privileged: true
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - VPN_ENABLED=yes
#      - VPN_TYPE=openvpn
#      - LAN_NETWORK=192.168.0.0/16
#    networks:
#      - caddy
#    volumes:
#      - qbittorrent:/config/
#      - blackhole:/blackhole/
#      - /mnt/download-cache/:/downloads/

volumes:
  sonarr:
    name: sonarr
  radarr:
    name: radarr
  lidarr:
    name: lidarr
  jackett:
    name: jackett
  blackhole:
    name: blackhole
  deluge:
    name: deluge
  #qbittorrent:
  #  name: qbittorrent

networks:
  torrent:
    name: torrent
#  caddy:
#    external: true