version: '3.9'
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      - wireguard
    ports:
      - "51820:51820/udp"
      - 5000:5000 # for wireguard-ui
    env_file: .env
    volumes:
      - wireguard:/config
      - /lib/modules:/lib/modules

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    restart: unless-stopped
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    env_file: .env
    volumes:
      - wireguard-ui:/app/db
      - wireguard:/etc/wireguard

volumes:
  wireguard:
    name: wireguard
  wireguard-ui:
    name: wireguard-ui

networks:
  wireguard:
    name: wireguard