name: Vaultwarden
services:
  vaultwarden:
    # https://github.com/dani-garcia/vaultwarden
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    env_file: vaultwarden.env
    depends_on:
      - vaultwarden-postgresql
    networks:
      - vaultwarden
    expose:
      - 80
    volumes:
      - vaultwarden:/data
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.rule: Host(`vault.domain.tld`)
      traefik.http.routers.vaultwarden.entrypoints: https
      traefik.http.routers.vaultwarden.middlewares: local-ip-ranges@file
      traefik.http.routers.vaultwarden.service: vaultwarden
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80

  vaultwarden-postgresql:
    # https://hub.docker.com/_/postgres
    image: postgres:18
    container_name: vaultwarden-postgresql
    restart: unless-stopped
    env_file: vaultwarden-postgresql.env
    networks:
      - vaultwarden
    expose:
      - 5432
    volumes:
      - vaultwarden-postgresql:/var/lib/postgresql


volumes:
  vaultwarden:
    name: vaultwarden
  vaultwarden-postgresql:
    name: vaultwarden-postgresql

networks:
  vaultwarden:
    name: vaultwarden
  traefik:
    external: true